"""empty message

Revision ID: 40100ca82072
Revises: 0763d677d453
Create Date: 2025-08-20 18:45:58.745565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40100ca82072'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
